### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Bonizhao** [MazzaWill/neo4j-python-pandas-py2neo-v3#21]
Traceback (most recent call last):
  File "C:\Users\35845\Desktop\程序\neo4j-python-pandas-py2neo-v3-master\lib\site-packages\py2neo\client\http.py", line 443, in from_json
    content = json_loads(data, object_hook=JSONHydrant.json_to_packstream)
  File "C:\Users\35845\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "C:\Users\35845\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\35845\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
运行时发生如上报错，该怎么修改呢，求大佬解惑

**Comment by MazzaWill** [comment]
Maintainer update (2026-06-01): this traceback usually means py2neo received an unexpected/non-JSON response from Neo4j, often because of a Neo4j URL/auth/version mismatch or because the project is being run on a newer Python/py2neo combination than the original baseline. The README now documents the known baseline: Python 3.6.5, Neo4j 3.x, and py2neo 3. If this is still reproducible, please add your Neo4j version, py2neo version, connection URL, and the command you ran so it can be triaged against the compatibility roadmap.
