### ISSUE TITLE
该项目在Win10上部署时neo4j注意事项

### ISSUE THREAD

**Issue by LMY-nlp0701** [MazzaWill/neo4j-python-pandas-py2neo-v3#8]
先看运行成功效果图：
<img width="960" alt="1" src="https://user-images.githubusercontent.com/33420219/89270558-1547e000-d66e-11ea-9ed8-74b88ef7d86d.png">

pycharm里的需要安装的包以及版本都在 [requirements.txt](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/requirements.txt) ，但是在还需要我们在Windows10上部署neo4j，下面是安装以及启动服务的注意事项。

**1.Windows10安装neo4j**
参考链接  [neo4j安装详细步骤](https://blog.csdn.net/JD_Wang0/article/details/104408190?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param)
注：该博客讲解的非常详细，请仔细按照步骤进行。

**2.启动neo4j服务**
<img width="541" alt="2" src="https://user-images.githubusercontent.com/33420219/89271378-32c97980-d66f-11ea-951c-bc139120c9d8.png">

2.1在浏览器输入 http://localhost:7474/browser/
<img width="960" alt="3" src="https://user-images.githubusercontent.com/33420219/89272145-4fb27c80-d670-11ea-9b6b-1431f6d75665.png">

2.2修改URL和设置用户名以及密码，与代码中的信息相符合
<img width="960" alt="4" src="https://user-images.githubusercontent.com/33420219/89272410-addf5f80-d670-11ea-9135-75d1d95c9515.png">

<img width="772" alt="5" src="https://user-images.githubusercontent.com/33420219/89272568-ed0db080-d670-11ea-872f-e0693e5b0f94.png">

**3.在pycharm里运行代码**
运行 invoice_neo4j.py 
注：修改一下该文件的 [invoice_neo4j.py](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/invoice_neo4j.py) 的第2行，包位置问题。
<img width="499" alt="6" src="https://user-images.githubusercontent.com/33420219/89272976-82a94000-d671-11ea-8c08-f48524b813b6.png">

**Comment by Greenhorntc** [comment]
great！ man

**Comment by renhuali** [comment]
我按照上面的修改了，但是现在只能显示出节点，不能显示节点之间的关系，请问你知道这要怎么解决吗，非常感谢！
![image](https://user-images.githubusercontent.com/74130418/101244896-1421df00-3744-11eb-831f-fc40e726d002.png)

**Comment by bibiup123** [comment]
> 先看运行成功效果图：
> <img alt="1" width="960" src="https://user-images.githubusercontent.com/33420219/89270558-1547e000-d66e-11ea-9ed8-74b88ef7d86d.png">
> 
> pycharm里的需要安装的包以及版本都在 [requirements.txt](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/requirements.txt) ，但是在还需要我们在Windows10上部署neo4j，下面是安装以及启动服务的注意事项。
> 
> **1.Windows10安装neo4j**
> 参考链接 [neo4j安装详细步骤](https://blog.csdn.net/JD_Wang0/article/details/104408190?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param)
> 注：该博客讲解的非常详细，请仔细按照步骤进行。
> 
> **2.启动neo4j服务**
> <img alt="2" width="541" src="https://user-images.githubusercontent.com/33420219/89271378-32c97980-d66f-11ea-951c-bc139120c9d8.png">
> 
> 2.1在浏览器输入 http://localhost:7474/browser/
> <img alt="3" width="960" src="https://user-images.githubusercontent.com/33420219/89272145-4fb27c80-d670-11ea-9b6b-1431f6d75665.png">
> 
> 2.2修改URL和设置用户名以及密码，与代码中的信息相符合
> <img alt="4" width="960" src="https://user-images.githubusercontent.com/33420219/89272410-addf5f80-d670-11ea-9135-75d1d95c9515.png">
> 
> <img alt="5" width="772" src="https://user-images.githubusercontent.com/33420219/89272568-ed0db080-d670-11ea-872f-e0693e5b0f94.png">
> 
> **3.在pycharm里运行代码**
> 运行 invoice_neo4j.py
> 注：修改一下该文件的 [invoice_neo4j.py](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/invoice_neo4j.py) 的第2行，包位置问题。
> <img alt="6" width="499" src="https://user-images.githubusercontent.com/33420219/89272976-82a94000-d671-11ea-8c08-f48524b813b6.png">

你好，我运行的时候显示py2neo模块有很多问题，可能是因为版本问题，但是我并没有找到版本为3的py2neo模块，应该怎么办呢？

**Comment by bibiup123** [comment]
> 我按照上面的修改了，但是现在只能显示出节点，不能显示节点之间的关系，请问你知道这要怎么解决吗，非常感谢！
> ![image](https://user-images.githubusercontent.com/74130418/101244896-1421df00-3744-11eb-831f-fc40e726d002.png)

请问你解决了吗？我也是同样的问题

**Comment by pickleHatter** [comment]
py2neo v4 doesn't has 'find_one' function.
In the place of find_one please change to NodeMatcher.

For example:
self.graph.find_one(label=self.invoice_name, property_key='name', property_value=df_data['name'][m])
change to:
from py2neo import Graph, NodeMatcher
matcher = NodeMatcher(self.graph)
matcher.match(self.invoice_name, name=df_data['name'][m]).first()

**Comment by liuxiaobei6667** [comment]
> py2neo v4 doesn't has 'find_one' function. In the place of find_one please change to NodeMatcher.
> 
> For example: self.graph.find_one(label=self.invoice_name, property_key='name', property_value=df_data['name'][m]) change to: from py2neo import Graph, NodeMatcher matcher = NodeMatcher(self.graph) matcher.match(self.invoice_name, name=df_data['name'][m]).first()

调整之后还是报错？怎么办Traceback (most recent call last):
  File "D:\python\lib\site-packages\py2neo\internal\connectors.py", line 372, in run
    raw_result = hydrator.hydrate_result(r.data.decode("utf-8"))
  File "D:\python\lib\site-packages\py2neo\internal\hydration\__init__.py", line 433, in hydrate_result
    raise HydrationError(*data["errors"])
py2neo.internal.hydration.HydrationError: {'code': 'Neo.ClientError.Statement.SyntaxError', 'message': 'Invalid input \'{\': expected "+" or "-" (line 1, column 31 (offset: 30))\r\n"MATCH (_:发票名称) WHERE _.name = {1} RETURN _"\r\n                               ^'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\知识图谱\neo4j-python-pandas-py2neo-v3-master\invoice_neo4j.py", line 76, in <module>
    create_data.create_relation(relation_extraction())
  File "D:\知识图谱\neo4j-python-pandas-py2neo-v3-master\dataToNeo4jClass\DataToNeo4jClass.py", line 33, in create_relation
    rel = Relationship(matcher.match(self.invoice_name, name=df_data['name'][m]).first(),
  File "D:\python\lib\site-packages\py2neo\matching.py", line 94, in first
    return self.graph.evaluate(*self._query_and_parameters())
  File "D:\python\lib\site-packages\py2neo\database.py", line 395, in evaluate
    return self.begin(autocommit=True).evaluate(cypher, parameters, **kwparameters)
  File "D:\python\lib\site-packages\py2neo\database.py", line 876, in evaluate
    return self.run(cypher, parameters, **kwparameters).evaluate(0)
  File "D:\python\lib\site-packages\py2neo\database.py", line 823, in run
    return Cursor(self.connector.run(statement=cypher,
  File "D:\python\lib\site-packages\py2neo\internal\connectors.py", line 377, in run
    raise GraphError.hydrate(e.args[0])
py2neo.database.ClientError: SyntaxError: Invalid input '{': expected "+" or "-" (line 1, column 31 (offset: 30))
"MATCH (_:发票名称) WHERE _.name = {1} RETURN _"

**Comment by Pony991215** [comment]
> 先看运行成功效果图： <img alt="1" width="960" src="https://user-images.githubusercontent.com/33420219/89270558-1547e000-d66e-11ea-9ed8-74b88ef7d86d.png">
> 
> pycharm里的需要安装的包以及版本都在 [requirements.txt](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/requirements.txt) ，但是在还需要我们在Windows10上部署neo4j，下面是安装以及启动服务的注意事项。
> 
> **1.Windows10安装neo4j** 参考链接 [neo4j安装详细步骤](https://blog.csdn.net/JD_Wang0/article/details/104408190?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param) 注：该博客讲解的非常详细，请仔细按照步骤进行。
> 
> **2.启动neo4j服务** <img alt="2" width="541" src="https://user-images.githubusercontent.com/33420219/89271378-32c97980-d66f-11ea-951c-bc139120c9d8.png">
> 
> 2.1在浏览器输入 http://localhost:7474/browser/ <img alt="3" width="960" src="https://user-images.githubusercontent.com/33420219/89272145-4fb27c80-d670-11ea-9b6b-1431f6d75665.png">
> 
> 2.2修改URL和设置用户名以及密码，与代码中的信息相符合 <img alt="4" width="960" src="https://user-images.githubusercontent.com/33420219/89272410-addf5f80-d670-11ea-9135-75d1d95c9515.png">
> 
> <img alt="5" width="772" src="https://user-images.githubusercontent.com/33420219/89272568-ed0db080-d670-11ea-872f-e0693e5b0f94.png">
> 
> **3.在pycharm里运行代码** 运行 invoice_neo4j.py 注：修改一下该文件的 [invoice_neo4j.py](https://github.com/Skyellbin/neo4j-python-pandas-py2neo-v3/blob/master/invoice_neo4j.py) 的第2行，包位置问题。 <img alt="6" width="499" src="https://user-images.githubusercontent.com/33420219/89272976-82a94000-d671-11ea-8c08-f48524b813b6.png">

您好，方便留个邮箱联系一下吗我这个程序连不上mysql数据库

**Comment by MazzaWill** [comment]
Maintainer update (2026-06-01): thanks for documenting the Windows 10 setup notes. I have labeled this as documentation/compatibility, and the README now includes setup and compatibility guidance. Closing this documentation note as captured; future Windows setup improvements will be tracked through new focused issues.
